name: HiddenArmor
version: '${projectVersion}'
main: me.kteq.hiddenarmor.HiddenArmor
api-version: "1.20"
authors: [ Kteq ]
description: Let players hide their armor and show off their skins
folia-supported: true
